Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: main
      CodeUri: C:\Development\share_frame\repos\user-management
      Runtime: go1.x
      Architectures:
        - x86_64